#!/usr/bin/env python
# coding: utf-8

# In[1]:


gene_begin='TCCTCCCTCCTGAAATAAGAAATTCATAGCTGGGGGTGGGGAGTAGATGGGGGCTGGGGGAAAAACTTTCTCACATTCACAGAGCAGCTTCCCTCAAAGCGGCACGGAATCGGGAACCCCACTCGGGACAGGGGAAAACGGCCAAGTTCCTAGAAATTTGTTTTCTTTGTGGGGAGCAATTCATGATGGGCGTTCTTGTCTGGTTTCCCCCCACTCCGTCCCCTGACGCCGAGTAACACTTAAACCTTTCTAGTTGCAAAGTCTTTTCAGAGTTTTTTTTTTAGGAAATAAGTTTTGAAAATTCTAGTGCTTAAAAAATGTGTATATATATATATATATATATATATATATATATATATATATATATATATATATATGTATATTTATAGCCTTTTATTTTCCCTGAGTACATGTTGGCCA'
gene_end='TTTGATAACTGATATCTAGTATGTATATATATATAAACAAAATGACGAGGACAGGGAATTTAATTATTTGGGTATCACACATGCAGGTGTTATATATGCCAAATTTTAAAGGTAAAATTTGTGTGAAATGTCACACTTTTATTATTTGTGTGAAATGTCATTTTACATATGGGTTCCATTTTGAAAGTGGTTTGGGAAGGGGGCATACCATTTTAAGTACCAAGAAAAACTTGCATAATCTCATTTTACTTTCTCTTTTTCAGCTGGATTTTCCTCTACGTGCTTCAGTCTTCTCTACACAAAGAGCTGCAAACCAGGTCTTTGTTTTGCACTCTTATTTCAAGCAGAATGAGTGCTCCTAAACTCCTCTCTCTGGGCTGTATCTTCTTCCCCTTGCTACTTTTTCAGCAGGCCCGGGCT'


class gene():
    def __init__(self,sequence):#make sure there are two underscores in a row before and after init
        self.sequence=sequence 
    def insertion_mutation(self):
        self.sequence += 'A'
        print (self.sequence)

        


# In[ ]:





# In[ ]:




